### ISSUE TITLE
Error when processing Chinese text

### ISSUE THREAD

**Issue by hitalex** [dasmith/stanford-corenlp-python#27]
After I start the server (with trained Chinese models and properties file), I test the server with a Chinese sentence by replacing the example English sentence in `client.py`, i.e.

```
#result = nlp.parse(u"Hello world!  It is so beautiful.")
result = nlp.parse(u"今天天气真不错啊！")
```

Traceback (most recent call last):
  File "client.py", line 17, in <module>
    result = nlp.parse(u"今天天气真不错啊！")
  File "client.py", line 13, in parse
    return json.loads(self.server.parse(text))
  File "/home/kqc/github/stanford-corenlp-python/jsonrpc.py", line 934, in **call**
    return self.__req(self.__name, args, kwargs)
  File "/home/kqc/github/stanford-corenlp-python/jsonrpc.py", line 907, in __req
    resp = self.__data_serializer.loads_response( resp_str )
  File "/home/kqc/github/stanford-corenlp-python/jsonrpc.py", line 626, in loads_response
    raise RPCInternalError(error_data)
jsonrpc.RPCInternalError: <RPCFault -32603: 'Internal error.' (None)>

Could you show me how to fix this?

**Comment by hitalex** [comment]
I fix this problem by myself.
The problem is not in transporting the text, but lines in the `pexpect` module. One should upgrade `pexpect` to v3 and use `pexpect.spawnu` to properly handle utf8 encodings.
For details, see: http://pexpect.readthedocs.org/en/latest/api/pexpect.html#handling-unicode

**Comment by wanglan0605** [comment]
When I try to parse Chinese texts with more than 1500 or 2000 Chinese words, the "result" returns nothing,just [ ].
Could you please show me how to fix it?
