### ISSUE TITLE
AttributeError: 'StanfordCoreNLP' object has no attribute 'parse_imperative' 

### ISSUE THREAD

**Issue by bcambel** [dasmith/stanford-corenlp-python#4]
Hi Dustin,

I am not sure if you are aware of the problem, when I try to run the corenlp.py, I get the following error

```
Starting the Stanford Core NLP parser.
Loading Models: 5/5 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| plays hard to get, smiles from time to time
NLP tools loaded.
Traceback (most recent call last):
  File "corenlp.py", line 295, in <module>
    server.register_function(nlp.parse_imperative)
AttributeError: 'StanfordCoreNLP' object has no attribute 'parse_imperative'
```

Commenting out the line 295 solved the problem. I have quickly scanned the code, and could not locate parse_imperative method. I am not very experienced with Python, may be I have missed something.

I wanted you to know

Thanks for the great work! Keep up.

**Comment by dasmith** [comment]
Thanks for the bug report!  The new version of Stanford's parser handles imperatives well, so I removed this function but forgot to remove it from the JSON-RPC.  I just fixed this with 8bbe6d15faf28cb9b4b25ee6f7d9c0c0344d70b7

Dustin
