### ISSUE TITLE
  File "corenlp.py", line 226     except Exception, e: Syntax error

### ISSUE THREAD

**Issue by justking14** [dasmith/stanford-corenlp-python#44]
Trying to run this in the terminal on my mac, but when I try running python corenlp.py, it gives me a syntax error at line 226 of corenlp.py.  Any way to fix this?  

I really need to get this working soon.

**Comment by vishalkejriwal** [comment]
How you resolved this?

**Comment by DenisPeskoff** [comment]
Same issue

**Comment by nazihbissat** [comment]
Same issue!

**Comment by RajaAyyanar** [comment]
Same Issue.

**Comment by HarmC** [comment]
replace the comma with the word `as`.
So `Exception as e:`
You will need to repeat this process in some other places of the project as well.
